<?php

/**
 * @file
 * Install and uninstall functions for the bombayliving.
 */

/**
 * Implements hook_install().
 */
function bombayliving_install() {
	// Set the weight of the mymodule.module to a value lower than views_datasource's views_json module.
  db_update('system')
   ->fields(array('weight' => -1))
   ->condition('name', 'bombayliving')
   ->execute();
}

/**
 * Implements hook_uninstall().
 */
function bombayliving_uninstall() {

}
